### ISSUE TITLE
Not in app store

### ISSUE THREAD

**Issue by timespacedecay** [CDsigma/Snapdrop-iOS-App#3]
Unless I'm stupid?  I don't see it in the iOS App Store.

**Comment by Wesley-Arrington** [comment]
Sorry, it is not in the App Store. I had only just started working on this project when my Macbook broke. Sadly I don't have another Apple computer and don't plan on buying one in the near future so this project won't see further development by me. Feel free to use this repo to compile the app onto your device or to fork the repo.
